version: '3'
services:

  redis.cache:
    image: "redis:latest"
    volumes:
      - ./volumes/db/redis/cache/jwt/data:/data
    ports:
      - 6379:6379 # для редактора

  db.mysql.posts:
    image: mysql/mysql-server:latest
    volumes:
      - './volumes/db/mysql/main:/var/lib/mysql'
    env_file:
      - ./.env
    ports:
      - 3306:3306 # для редактора

  node.backend:
    build: ./node_back
    volumes:
      - ./node_back:/usr/src/app
    depends_on:
      - 'db.mysql.posts'
      - 'redis.cache'
    env_file:
      - ./.env
    command: sh -c " yarn install && yarn start "
    ports:
      - 3000:3000
    restart: always

  front.vue:
    build: ./front_vue
    volumes:
      - ./front_vue:/usr/src/app
    command: sh -c " yarn install && yarn dev "
    depends_on: 
      - node.backend
    restart: always
  
  minio.storage:
    image: minio/minio:latest
    ports:
     - 9000:9000
     - 9009:9009
    volumes:
      - ./volumes/minio/storage:/data
    env_file:
      - ./.env
    command: server --console-address :9009 /data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - front.vue
      - node.backend
    restart: always